# Generated by Django 4.2 on 2023-05-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('JP', 'Japan'), ('CN', 'China'), ('TW', 'Taiwan')], max_length=2),
        ),
    ]
