# Generated by Django 4.2 on 2023-05-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_userprofile_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mail',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
