# Generated by Django 4.2 on 2023-05-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('F', '女'), ('U', '不透露'), ('M', '男')], max_length=1),
        ),
    ]
