# Generated by Django 4.2 on 2023-04-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_updata_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='updata_music',
            name='artist_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
