# Generated by Django 4.2 on 2023-04-10 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_updata_music_artist_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='updata_music',
            new_name='music',
        ),
    ]
