# Generated by Django 4.2 on 2023-05-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='country',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mail',
            field=models.EmailField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
