# Generated by Django 4.2 on 2023-05-05 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='電話號碼錯誤、應在9～15個數字之間 ＋號可有可無', regex='^\\+?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='使用者名稱錯誤、應在1～10個字之間', regex='^.{1,10}$')]),
        ),
    ]
