# Generated by Django 4.2 on 2023-05-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(choices=[('NN', '不透露'), ('US', 'United States'), ('CA', 'Canada'), ('JP', 'Japan'), ('CN', 'China'), ('TW', 'Taiwan'), ('KR', 'Korea'), ('SG', 'Singapore'), ('MY', 'Malaysia'), ('TH', 'Thailand'), ('PH', 'Philippines'), ('ID', 'Indonesia')], max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('F', '女'), ('M', '男'), ('U', '不透露')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
