# Generated by Django 4.2 on 2023-05-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('U', '不透露'), ('F', '女')], max_length=1),
        ),
    ]
